INSERT INTO treks (name, slug, location, state, country, difficulty, distance_km, duration_days, altitude_meters, best_season, description, image_url, latitude, longitude, created_at) VALUES
('Kedarkantha Trek', 'kedarkantha-trek', 'Sankri', 'Uttarakhand', 'India', 'EASY', 20.00, 5, 3810, 'December to April', 'A classic winter trek with snow-covered pine forests and panoramic Himalayan summit views.', NULL, 31.0100000, 78.1800000, CURRENT_TIMESTAMP(6)),
('Valley of Flowers Trek', 'valley-of-flowers-trek', 'Govindghat', 'Uttarakhand', 'India', 'MODERATE', 38.00, 6, 3658, 'July to September', 'A monsoon trek through a UNESCO-listed alpine valley filled with endemic Himalayan flowers.', NULL, 30.7280000, 79.6050000, CURRENT_TIMESTAMP(6)),
('Hampta Pass Trek', 'hampta-pass-trek', 'Manali', 'Himachal Pradesh', 'India', 'MODERATE', 35.00, 5, 4270, 'June to October', 'A dramatic crossover trek linking the green Kullu valley to the barren landscapes of Lahaul.', NULL, 32.2360000, 77.4120000, CURRENT_TIMESTAMP(6)),
('Chadar Trek', 'chadar-trek', 'Leh', 'Ladakh', 'India', 'CHALLENGING', 62.00, 9, 3390, 'January to February', 'A demanding winter journey over the frozen Zanskar River in Ladakh.', NULL, 34.1526000, 77.5771000, CURRENT_TIMESTAMP(6)),
('Sandakphu Trek', 'sandakphu-trek', 'Manebhanjan', 'West Bengal', 'India', 'MODERATE', 52.00, 6, 3636, 'March to May and October to December', 'The highest trek in West Bengal, renowned for views of Everest, Kanchenjunga, Lhotse and Makalu.', NULL, 27.1100000, 88.0000000, CURRENT_TIMESTAMP(6)),
('Roopkund Trek', 'roopkund-trek', 'Lohajung', 'Uttarakhand', 'India', 'DIFFICULT', 53.00, 8, 5029, 'May to June and September to October', 'A high-altitude Himalayan trek leading toward the mysterious glacial lake of Roopkund.', NULL, 30.2590000, 79.7330000, CURRENT_TIMESTAMP(6)),
('Goechala Trek', 'goechala-trek', 'Yuksom', 'Sikkim', 'India', 'DIFFICULT', 65.00, 11, 4940, 'April to May and October to November', 'A magnificent Sikkim trek offering close views of Kanchenjunga and the Samiti Lake basin.', NULL, 27.3670000, 88.2340000, CURRENT_TIMESTAMP(6)),
('Tarsar Marsar Trek', 'tarsar-marsar-trek', 'Aru', 'Jammu and Kashmir', 'India', 'MODERATE', 48.00, 7, 3795, 'July to September', 'An alpine Kashmir trek connecting two beautiful high-altitude lakes amid meadows and ridges.', NULL, 34.0830000, 75.2500000, CURRENT_TIMESTAMP(6)),
('Kashmir Great Lakes Trek', 'kashmir-great-lakes-trek', 'Sonamarg', 'Jammu and Kashmir', 'India', 'MODERATE', 72.00, 8, 4200, 'July to September', 'A high mountain route through a chain of turquoise alpine lakes in Kashmir.', NULL, 34.3030000, 75.5050000, CURRENT_TIMESTAMP(6)),
('Brahmatal Trek', 'brahmatal-trek', 'Lohajung', 'Uttarakhand', 'India', 'EASY', 24.00, 6, 3734, 'December to March', 'A winter-friendly Himalayan trek with frozen lake views and a broad Trishul panorama.', NULL, 30.1890000, 79.6280000, CURRENT_TIMESTAMP(6));
