CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating INTEGER NOT NULL,
    comment VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    trek_id BIGINT NOT NULL,
    CONSTRAINT uk_reviews_user_trek UNIQUE (user_id, trek_id),
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_reviews_trek FOREIGN KEY (trek_id) REFERENCES treks (id)
);
