server:
  forward-headers-strategy: framework
  error:
    include-stacktrace: never
    include-message: never
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/javascript,text/css,text/html,text/plain

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  mvc:
    problemdetails:
      enabled: false

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:false}
  swagger-ui:
    enabled: ${SPRINGDOC_ENABLED:false}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:WARN}
    com.trekmate: ${LOG_LEVEL_APP:INFO}

app:
  jwt:
    secret: ${JWT_SECRET}
