import { useQuery } from '@tanstack/react-query';
import { Link, useNavigate } from 'react-router-dom';
import { getTreks } from '../api/treks';
import { SearchBar } from '../components/treks/SearchBar';
import { TrekCard } from '../components/treks/TrekCard';
import { TrekSkeleton } from '../components/treks/TrekSkeleton';
import { Seo } from '../components/common/Seo';

export function HomePage() {
  const navigate = useNavigate();
  const treks = useQuery({ queryKey: ['treks', 'featured'], queryFn: () => getTreks({ size: 3, sort: 'newest' }) });
  return <div className="-mx-4 -mt-8 sm:-mx-6 animate-enter"><Seo title="Discover Indian treks"/><section className="relative overflow-hidden bg-slate-950 px-4 py-20 text-white sm:px-6 lg:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,_rgba(16,185,129,.30),_transparent_35%),radial-gradient(circle_at_bottom_left,_rgba(14,165,233,.20),_transparent_35%)]"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-sm font-bold uppercase tracking-[.25em] text-emerald-300">India, one trail at a time</p><h1 className="mt-5 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Find the trek that changes your perspective.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Thoughtfully discover Himalayan adventures, compare conditions, and plan with confidence.</p><div className="mt-9 max-w-2xl"><SearchBar onSearch={(keyword) => navigate(`/treks?keyword=${encodeURIComponent(keyword)}`)} /></div></div><HeroTrailVisual /></div></section><section className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-700 dark:text-emerald-400">Start exploring</p><h2 className="mt-2 text-3xl font-bold">Recently added treks</h2></div><Link to="/treks" className="font-semibold text-emerald-700 dark:text-emerald-400">View all →</Link></div><div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3" aria-live="polite">{treks.isLoading ? Array.from({ length: 3 }, (_, index) => <TrekSkeleton key={index} />) : treks.data?.content.map((trek) => <TrekCard key={trek.id} trek={trek} />)}</div>{treks.isError && <p role="alert" className="mt-6 rounded-lg bg-rose-50 p-4 text-rose-700 dark:bg-rose-950/50 dark:text-rose-300">Treks could not be loaded. Sign in to the backend, then try again.</p>}</section></div>;
}

function HeroTrailVisual() {
  return <div className="relative mx-auto hidden aspect-square w-full max-w-md lg:block" aria-hidden="true"><div className="absolute inset-0 rounded-full border border-emerald-300/20"/><div className="absolute inset-8 rounded-full border border-emerald-300/20"/><div className="absolute inset-16 rounded-full border border-emerald-300/20"/><div className="absolute left-[12%] top-[18%] h-3 w-3 rounded-full bg-emerald-300 shadow-[0_0_20px_7px_rgba(110,231,183,.4)]"/><div className="absolute right-[16%] top-[40%] h-3 w-3 rounded-full bg-sky-300 shadow-[0_0_20px_7px_rgba(125,211,252,.4)]"/><div className="absolute bottom-[16%] left-[38%] h-3 w-3 rounded-full bg-amber-200 shadow-[0_0_20px_7px_rgba(253,230,138,.4)]"/><div className="absolute left-[18%] top-[24%] h-[2px] w-[62%] rotate-[24deg] bg-gradient-to-r from-emerald-300 via-sky-300 to-transparent"/><div className="absolute left-[38%] top-[53%] h-[2px] w-[30%] -rotate-[58deg] bg-gradient-to-r from-sky-300 via-amber-200 to-transparent"/><div className="absolute inset-[28%] grid place-items-center rounded-3xl border border-white/20 bg-slate-950/60 p-5 shadow-2xl backdrop-blur"><span className="text-5xl">⌂</span><p className="mt-3 text-center text-sm font-bold uppercase tracking-[.2em] text-emerald-200">Trail explorer</p><p className="mt-2 text-center text-xs text-slate-400">Discover 10 iconic Indian treks</p></div></div>;
}
