import { AxiosError } from 'axios';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { register as registerAccount } from '../api/auth';
import { AuthCard } from '../components/auth/AuthCard';
import { useAuth } from '../contexts/AuthContext';
import type { RegisterRequest } from '../types/auth';

type RegisterForm = RegisterRequest & { confirmPassword: string };
export function RegisterPage() { const { completeLogin } = useAuth(); const navigate = useNavigate(); const { register, handleSubmit, watch, formState: { errors, isSubmitting }, setError } = useForm<RegisterForm>(); const password = watch('password'); const submit = async ({ confirmPassword: _confirmPassword, ...values }: RegisterForm) => { try { completeLogin(await registerAccount(values)); navigate('/'); } catch (error) { const message = error instanceof AxiosError ? error.response?.data?.message : undefined; setError('root', { message: message || 'We could not create your account. Try a different email.' }); } }; return <AuthCard title="Start your trail story" subtitle="Create an account to save the adventures that call to you."><form onSubmit={handleSubmit(submit)} noValidate className="space-y-5"><Field label="Name" error={errors.name?.message}><input autoComplete="name" {...register('name', { required: 'Enter your name.', maxLength: { value: 100, message: 'Name must be 100 characters or fewer.' } })}/></Field><Field label="Email address" error={errors.email?.message}><input type="email" autoComplete="email" {...register('email', { required: 'Enter your email address.', pattern: { value: /^\S+@\S+\.\S+$/, message: 'Enter a valid email address.' } })}/></Field><Field label="Password" error={errors.password?.message}><input type="password" autoComplete="new-password" {...register('password', { required: 'Create a password.', minLength: { value: 8, message: 'Use at least 8 characters.' } })}/></Field><Field label="Confirm password" error={errors.confirmPassword?.message}><input type="password" autoComplete="new-password" {...register('confirmPassword', { required: 'Confirm your password.', validate: (value) => value === password || 'Passwords do not match.' })}/></Field>{errors.root && <p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/50 dark:text-rose-300">{errors.root.message}</p>}<button disabled={isSubmitting} className="w-full rounded-xl bg-emerald-600 px-4 py-3 font-bold text-white hover:bg-emerald-500 disabled:opacity-60">{isSubmitting ? 'Creating account…' : 'Create account'}</button></form><p className="mt-6 text-center text-sm text-slate-600 dark:text-slate-400">Already have an account? <Link to="/login" className="font-bold text-emerald-700 dark:text-emerald-400">Sign in</Link></p></AuthCard>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold">{label}<span className="mt-2 block [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-300 [&_input]:bg-transparent [&_input]:px-3 [&_input]:py-3 [&_input]:font-normal [&_input]:outline-none [&_input]:focus:border-emerald-500 dark:[&_input]:border-slate-700">{children}</span>{error && <span className="mt-1 block text-xs font-normal text-rose-600 dark:text-rose-400">{error}</span>}</label>; }
