import { useQuery } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { getTreks } from '../api/treks';
import { FilterSidebar } from '../components/treks/FilterSidebar';
import { Pagination } from '../components/treks/Pagination';
import { SearchBar } from '../components/treks/SearchBar';
import { TrekCard } from '../components/treks/TrekCard';
import { TrekSkeleton } from '../components/treks/TrekSkeleton';
import { EmptyState } from '../components/common/EmptyState';
import { Seo } from '../components/common/Seo';
import type { Difficulty, TrekSearchParams } from '../types/trek';

function toFilters(params: URLSearchParams): TrekSearchParams { return { keyword: params.get('keyword') ?? undefined, state: params.get('state') ?? undefined, difficulty: (params.get('difficulty') as Difficulty | null) ?? undefined, season: params.get('season') ?? undefined, minDurationDays: params.get('minDurationDays') ? Number(params.get('minDurationDays')) : undefined, maxDurationDays: params.get('maxDurationDays') ? Number(params.get('maxDurationDays')) : undefined, sort: (params.get('sort') as TrekSearchParams['sort'] | null) ?? 'name', page: Number(params.get('page') ?? 0), size: 9 }; }

export function TrekListPage() {
  const [searchParams, setSearchParams] = useSearchParams(); const filters = toFilters(searchParams);
  const update = (next: TrekSearchParams) => { const query = new URLSearchParams(); Object.entries(next).forEach(([key, value]) => { if (value !== undefined && value !== '' && key !== 'size') query.set(key, String(value)); }); setSearchParams(query); };
  const treks = useQuery({ queryKey: ['treks', filters], queryFn: () => getTreks(filters) });
  return <section className="animate-enter"><Seo title="Explore treks"/><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-wider text-emerald-700 dark:text-emerald-400">Trek catalogue</p><h1 className="mt-2 text-4xl font-bold tracking-tight">Find your next summit</h1><p className="mt-3 text-slate-600 dark:text-slate-400">Filter trails by season, difficulty and duration to make your next escape feel just right.</p></div><div className="mt-8"><SearchBar initialValue={filters.keyword} onSearch={(keyword) => update({ ...filters, keyword: keyword || undefined, page: 0 })} /></div><div className="mt-8 grid gap-8 lg:grid-cols-[260px_1fr]"><FilterSidebar filters={filters} onChange={update} onClear={() => update({ sort: 'name', page: 0, size: 9 })}/><div><div className="flex flex-wrap items-center justify-between gap-4"><p className="text-sm text-slate-500" aria-live="polite">{treks.data ? `${treks.data.totalElements} treks found` : 'Finding treks…'}</p><label className="text-sm font-medium">Sort by <select value={filters.sort} onChange={(event) => update({ ...filters, sort: event.target.value as TrekSearchParams['sort'], page: 0 })} className="ml-2 rounded-lg border border-slate-300 bg-transparent px-3 py-2 dark:border-slate-700"><option value="name">Name</option><option value="altitude">Altitude</option><option value="distance">Distance</option><option value="newest">Newest</option></select></label></div>{treks.isError ? <div role="alert" className="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-5 text-rose-800 dark:border-rose-900 dark:bg-rose-950/50 dark:text-rose-300">Unable to load treks. The TrekMate backend requires a valid sign-in token.</div> : <><div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{treks.isLoading ? Array.from({ length: 6 }, (_, index) => <TrekSkeleton key={index} />) : treks.data?.content.map((trek) => <TrekCard key={trek.id} trek={trek} />)}</div>{treks.data?.content.length === 0 && <div className="mt-6"><EmptyState title="No treks match these filters" description="Broaden your search or clear the filters to discover more trails." action={<button onClick={() => update({ sort: 'name', page: 0, size: 9 })} className="font-bold text-emerald-700 dark:text-emerald-400">Clear all filters</button>}/></div>}<Pagination page={treks.data?.number ?? 0} totalPages={treks.data?.totalPages ?? 0} onChange={(page) => update({ ...filters, page })}/></>}</div></div></section>;
}
