import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createReview, deleteReview, getReviews, updateReview, type Review, type ReviewRequest } from '../../api/reviews';
import { useAuth } from '../../contexts/AuthContext';
import { EmptyState } from '../common/EmptyState';

export function ReviewsSection({ trekId }: { trekId: number }) {
  const { user } = useAuth(); const queryClient = useQueryClient(); const [editing, setEditing] = useState<Review | null>(null);
  const reviews = useQuery({ queryKey: ['reviews', trekId], queryFn: () => getReviews(trekId) });
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ['reviews', trekId] });
  const remove = useMutation({ mutationFn: deleteReview, onSuccess: invalidate });
  return <section className="mt-12 border-t border-slate-200 pt-10 dark:border-slate-800"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-700 dark:text-emerald-400">Community</p><h2 className="mt-2 text-2xl font-bold">Reviews</h2></div>{reviews.data && <p className="text-sm text-slate-600 dark:text-slate-400">{reviews.data.reviewCount ? <><span className="font-bold text-slate-900 dark:text-white">★ {Number(reviews.data.averageRating).toFixed(1)}</span> · {reviews.data.reviewCount} {reviews.data.reviewCount === 1 ? 'review' : 'reviews'}</> : 'No reviews yet'}</p>}</div>{user && <ReviewForm key={editing?.id ?? 'new'} trekId={trekId} review={editing} onDone={() => setEditing(null)} />}{reviews.isLoading ? <div className="mt-6 space-y-4">{[1, 2].map((item) => <div key={item} className="h-28 animate-pulse rounded-xl bg-slate-200 dark:bg-slate-800" />)}</div> : reviews.isError ? <p role="alert" className="mt-6 rounded-xl bg-rose-50 p-4 text-sm text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">Reviews could not be loaded. Please try again.</p> : reviews.data?.reviews.length === 0 ? <div className="mt-6"><EmptyState title="No reviews yet" description="Be the first to review this trek." /></div> : <div className="mt-6 space-y-4">{reviews.data?.reviews.map((review) => <article key={review.id} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{review.userName}</p><p className="mt-1 text-sm text-amber-500" aria-label={`${review.rating} out of 5 stars`}>{'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}</p></div><time className="text-xs text-slate-500">{new Date(review.createdAt).toLocaleDateString()}</time></div><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{review.comment}</p>{user?.id === review.userId && <div className="mt-4 flex gap-3"><button onClick={() => setEditing(review)} className="text-sm font-bold text-emerald-700 dark:text-emerald-400">Edit</button><button disabled={remove.isPending} onClick={() => { if (window.confirm('Delete your review?')) remove.mutate(review.id); }} className="text-sm font-bold text-rose-700 dark:text-rose-300">Delete</button></div>}</article>)}</div>}</section>;
}

function ReviewForm({ trekId, review, onDone }: { trekId: number; review: Review | null; onDone: () => void }) {
  const queryClient = useQueryClient(); const [rating, setRating] = useState(review?.rating ?? 5); const [comment, setComment] = useState(review?.comment ?? ''); const [error, setError] = useState('');
  const mutation = useMutation({ mutationFn: (request: ReviewRequest) => review ? updateReview(review.id, request) : createReview(trekId, request), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['reviews', trekId] }); setComment(''); onDone(); }, onError: () => setError('Unable to save your review. Please try again.') });
  const submit = (event: FormEvent) => { event.preventDefault(); if (comment.trim().length === 0) return setError('Write a review before submitting.'); mutation.mutate({ rating, comment: comment.trim() }); };
  return <form onSubmit={submit} className="mt-6 rounded-xl bg-slate-100 p-5 dark:bg-slate-900"><h3 className="font-bold">{review ? 'Edit your review' : 'Share your experience'}</h3><fieldset className="mt-3 flex gap-1"><legend className="sr-only">Rating</legend>{[1, 2, 3, 4, 5].map((value) => <button key={value} type="button" onClick={() => setRating(value)} aria-label={`${value} star${value === 1 ? '' : 's'}`} aria-pressed={rating === value} className={`text-2xl ${value <= rating ? 'text-amber-500' : 'text-slate-400'}`}>★</button>)}</fieldset><textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength={2000} rows={4} className="mt-3 w-full rounded-lg border border-slate-300 bg-white p-3 text-sm text-slate-900 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100" placeholder="What should future trekkers know?" />{error && <p role="alert" className="mt-2 text-sm text-rose-700 dark:text-rose-300">{error}</p>}<div className="mt-3 flex gap-3"><button disabled={mutation.isPending} className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-60">{mutation.isPending ? 'Saving…' : review ? 'Update review' : 'Submit review'}</button>{review && <button type="button" onClick={onDone} className="text-sm font-bold">Cancel</button>}</div></form>;
}
